### ISSUE TITLE
在这里讨论一些翻译的约定和规范

### ISSUE THREAD

**Issue by ya-luotao** [Leolusir/github-developer-guides#2]
可以现在在这里讨论，然后再整理到 README 里去

**Comment by ya-luotao** [comment]
- Repository 是直接使用还是翻译成「仓库」或者「代码仓库」？
- Merge 是翻译成「合并」还是直接使用？

**Comment by Leolusir** [comment]
Respository直接使用仓库,merge使用英文

**Comment by ya-luotao** [comment]
那merge使用英文的话，created repository是翻译成创建还是直接使用？因为很多地方都是把merge和create放到一起说的，而这两个词又都是同一类型的，是不是要统一下 _(:зゝ∠)_
